### ISSUE TITLE
Underwater Bubble Rendering

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#10]
I noticed that the bubbles that emit from Knuckles and Rouge's mouths when they're underwater only render whenever they're in front of the character models, and they seem to render behind the stages when not in front of them.
![Knunckles BubbleDC](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/acf7f5a8-dc43-480d-bd02-481b59a15008)
![Knuckles BubbleBattle](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/0b9f583b-0811-44df-b0e5-edb89842b12a)
![Rouge BubbleDC](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/420b0af6-c970-43bf-99fc-5a3df7197374)
![Rouge BubbleBattle](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/855ae056-165e-4d21-b69e-c5c2876e23d5)

**Comment by shaddatic** [comment]
Ignoring the last image as that's a seperate issue. This could be super easy to fix or quite messy, but either way will be looked into. Issue related to issue #1.

**Comment by shaddatic** [comment]
This issue is fixed as of version 1.2!
