### ISSUE TITLE
Shadow Maps Can't Cast on Chunk Models

### ISSUE THREAD

**Issue by san7326** [shaddatic/sa2b-render-fix#100]
![Screenshot_61](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/d45c38be-a94a-4ece-a196-1d2670808832)
![Screenshot_62](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/42731a73-f60e-4543-805e-c66cbdf6bfbb)
![Screenshot_63](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/fce51bd6-a07a-4f99-9e77-da40b1bd1eb6)

It happens a lot in Pyramid Cave
![Screenshot_64](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/62a12c78-91e2-43ba-9f6b-2643b0f61d89)
![Screenshot_65](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/f62a38c5-9aba-4ac3-8bc3-00c057b646df)
![Screenshot_66](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/5892b087-fed2-49c9-9889-4c4fa749776d)

**Comment by shaddatic** [comment]
This is a known issue with the vanilla system, it can't cast on the Dreamcast's 'Chunk' models, only the models in the GameCube format. It's been slowly looked into, but will need to be solved for Dreamcast level ports

**Comment by shaddatic** [comment]
This issue is fixed as of 1.3.3
