### ISSUE TITLE
SA2 (Comic Sans) option has grey pause menu text

### ISSUE THREAD

**Issue by kadaj29** [shaddatic/sa2b-render-fix#101]
When configuring the mod to select the original font used in the DC/GCN version, the non-selected pause menu text is grey like in the PC port. In the releases of the game that used this font, the letters were light blue instead.

DC/GCN: 
![dc](https://github.com/shaddatic/sa2b-render-fix/assets/57066321/fba51e45-6af8-480d-81e7-4dca3c6f1cd6)

PC with Render Fix:
![pc](https://github.com/shaddatic/sa2b-render-fix/assets/57066321/a8dcc184-afce-471b-b931-04519352d6cc)

**Comment by shaddatic** [comment]
I thought I noticed this. They probably changed the color at some point to better match the new fonts. This is something I'll look into for a future update!
