### ISSUE TITLE
Vehicles are invisible in Big Foot boss stage when Transparency Sorting Fixes is enabled

### ISSUE THREAD

**Issue by cnrm** [shaddatic/sa2b-render-fix#103]
When Transparency Sorting Fixes is enabled, the cars surrounding Big Foot's stage seem to mostly disappear.

No mods, codes or patches besides Render Fix were enabled while diagnosing the problem. All other Render Fix settings were tested.

Enabled:
![sonic2app_2024-06-11_07-46-54](https://github.com/shaddatic/sa2b-render-fix/assets/5803611/dce07c42-2355-4915-adbf-bafdc20793b6)

Disabled:
![sonic2app_2024-06-11_07-51-33](https://github.com/shaddatic/sa2b-render-fix/assets/5803611/5449b992-07bd-4aa8-a5fd-bd7d51b1f078)

**Comment by shaddatic** [comment]
I know what's happening here, I'll get it fixed for the next minor update
