### ISSUE TITLE
Pyramid Cave crash with DXVK

### ISSUE THREAD

**Issue by NolanHewitt** [shaddatic/sa2b-render-fix#107]
Using DXVK 2.4 causes this level to crash consistently on start up. This mod has me install this, so I reported this issue both here and to the github for DXVK

A crash message occurs on crash as well: 

"SA2 has crashed at 757cf5c2 (msvcrt.dll)."

[sonic2app_d3d9.log](https://github.com/user-attachments/files/16313989/sonic2app_d3d9.log)
The crash log suggests a memory allocation issue?

**Comment by shaddatic** [comment]
Yeah, this is likely just a DXVK issue that will be fixed. Not much I can do on my side, since the legacy version the mod is shipped with is fine. I'll leave the issue open though until it's fixed on DXVK's side

**Comment by shaddatic** [comment]
I think it's fair to close this now
