### ISSUE TITLE
Death Chamber/Egg Quarters - Key object is missing glowing eyes

### ISSUE THREAD

**Issue by ConnoisseurDexterity** [shaddatic/sa2b-render-fix#108]
![EQ key object glow](https://github.com/user-attachments/assets/c55220bb-3cf7-4d6c-8444-cfbad6b5978d)

In the Dreamcast version, the eyes of this key object glow. This is missing in the ports.

**Comment by shaddatic** [comment]
Thanks goes to End User for figuring out the mistake!

![image](https://github.com/user-attachments/assets/efff4435-2c3e-4c6d-88ff-8abe3f412d3a)
