### ISSUE TITLE
Random Polygon Stretching In Cutscenes

### ISSUE THREAD

**Issue by toonjoey** [shaddatic/sa2b-render-fix#116]
After the new Render Fix update, there seems to be an issue where random polygons in cutscenes are stretched.

From the little I've played, I noticed:

- The missiles in Sonic's City Escape intro
![image](https://github.com/user-attachments/assets/332e562e-628e-42c7-a256-822e7c0f27b1)

- Knuckles in the Knuckles intro cutscene (this also happened to his gloves)
![image](https://github.com/user-attachments/assets/fe97e817-db9d-44e4-803d-15d1107e9082)

This is consistent between viewings.

**Comment by shaddatic** [comment]
I'm unable to reproduce this. Have you checked your mods?

**Comment by toonjoey** [comment]
Just checked, this seems to be an issue with Cutscene Revamp, which is disappointing to say the least. My apologies!

**Comment by shaddatic** [comment]
I should mention, I also cannot reproduce this with Cutscene Revamp enabled either

**Comment by toonjoey** [comment]
All I know is the moment I disabled it the issue went away. Weird.
