### ISSUE TITLE
2D explosions don't render behind 3D explosions

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#121]
The 2D explosions effects disappear behind 3D explosion effects which makes for a real weird look when the 3D explosions fade out.
PC
![image](https://github.com/user-attachments/assets/c7d04b66-8faf-4341-96cb-555d2b0b6d14)
DC
![image](https://github.com/user-attachments/assets/191d8dfe-5d44-4d5e-9d4f-20450d31ecc9)

**Comment by shaddatic** [comment]
Issue is fixed as of 1.3.3 with a texture flag change
