### ISSUE TITLE
Cutscenes forced into 4:3 aspect ratio with black bars

### ISSUE THREAD

**Issue by NikkMann** [shaddatic/sa2b-render-fix#126]
Like the title says.

If you try to use SA2 Render Fix with Cutscene Revamp or the new SA2B Directors Cut mod, cutscenes will always show in 4:3 with black bars on the sides, even if 16:9 is selected in the other mod.

Tested this by having only cutscene revamp (16:9 cutscenes worked fine) and then only enabling SA2 Render Fix (cutscenes went back to 4:3). Load order doesn't matter.

**Comment by toonjoey** [comment]
This is a toggle in Render Fix that is enabled by default.

**Comment by NikkMann** [comment]
Yep, I see it now
