### ISSUE TITLE
Some weird lighting. Not sure if it's intentional.

### ISSUE THREAD

**Issue by Sonic-Man88** [shaddatic/sa2b-render-fix#127]
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 37 16 08" src="https://github.com/user-attachments/assets/685e6bcb-5d5d-4a1e-8da0-77136bc5fb8b">
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 37 52 81" src="https://github.com/user-attachments/assets/9adae682-eb94-4883-b752-baef5423dcd4">
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 38 10 08" src="https://github.com/user-attachments/assets/132c529f-1e7b-4b2e-9c04-5fbeb8050873">
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 38 11 63" src="https://github.com/user-attachments/assets/005c9842-eb15-49a0-a66a-2276c8eb0106">
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 38 15 70" src="https://github.com/user-attachments/assets/a90db27c-4e44-4d8a-a8d6-9cc25cad5a9a">
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 38 17 27" src="https://github.com/user-attachments/assets/f2dc4d57-c2db-44fb-b698-4c3fdbe2b808">
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 38 18 02" src="https://github.com/user-attachments/assets/720f67ae-9f6a-4840-a7ad-d26419e632ae">
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 38 23 22" src="https://github.com/user-attachments/assets/2615fac0-91ff-43d3-947e-d9d447e7fe32">
<img width="960" alt="Sonic Adventure 2 Screenshot 2024 10 04 - 06 38 31 31" src="https://github.com/user-attachments/assets/9b7aea11-7505-4c85-bc3e-3524fd6b098b">

**Comment by shaddatic** [comment]
Sorry, I don't know what you're pointing out. Could you be more specific?

**Comment by shaddatic** [comment]
Closing as invalid
