### ISSUE TITLE
Shadow on Sonic's model

### ISSUE THREAD

**Issue by Cole144** [shaddatic/sa2b-render-fix#128]
Hi, is there any way to fix this?
![20241029231319_1](https://github.com/user-attachments/assets/b46d670c-de12-434c-b460-07482eee3c7d)
![20241029231413_1](https://github.com/user-attachments/assets/c3ba4e6c-e214-447e-b539-0b864744c135)
![20241029231617_1](https://github.com/user-attachments/assets/3aeebbf8-a68e-4349-b225-3fada239ec12)

**Comment by shaddatic** [comment]
This is not a bug, and is working as intended. Modifier shadows, or Dreamcast shadows, cast on many objects including the player.

A setting is planned to disable player shadowing for those who really can't stand it but it will likely look visually disjointed; as many other objects, like Chao and Minimals, will be effected by shadows but the player won't.

**Comment by Cole144** [comment]
> This is not a bug, and is working as intended. Modifier shadows, or Dreamcast shadows, cast on many objects including the player.
> 
> A setting is planned to disable player shadowing for those who really can't stand it but it will likely look visually disjointed; as many other objects, like Chao and Minimals, will be effected by shadows but the player won't.

Got it, thx
