### ISSUE TITLE
Tails and Rouge are still tinted in Route 101/Route 280

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#17]
![TailsDarken](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/339f7101-9720-4693-99da-ea700cfb55f6)
![RougeDarken](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/0cfe049f-8c14-4a61-9b16-24f89b75d2f6)

**Comment by shaddatic** [comment]
That was a long search haha. The models for all the carts are stored in Data.dll, but I managed to track them down, decomp the struct they're stored in, and successfully un-tint them! Leaving open for a little bit just to make sure they don't look too bright now.

![213610_20230701133215_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/983ba180-825a-4583-b3e5-b9c48ba49945)
