### ISSUE TITLE
Missing Route 101/Route 280 Billboards

### ISSUE THREAD

**Issue by LostImpactProd** [shaddatic/sa2b-render-fix#18]
Would like to see the kart stages' billboards restored to the game (with perhaps toggles for DC, GC or combined billboard textures?).

![Sa2_billboardsdreamcast](https://github.com/shaddatic/sa2b-render-fix/assets/138042750/74cc5f94-bd83-4c83-91bb-eea68d1a0d91)

![Sa2_billboardspc](https://github.com/shaddatic/sa2b-render-fix/assets/138042750/1b284a47-6d73-4c82-b9bf-551559590b24)

**Comment by LostImpactProd** [comment]
Would like to see the kart stages' billboards restored to the game (with perhaps toggles for DC, GC or combined billboard textures).

![Sa2_billboardsdreamcast](https://github.com/shaddatic/sa2b-render-fix/assets/138042750/c5d1e0ab-465c-4fa1-9922-702a7826a89e)

![Sa2_billboardspc](https://github.com/shaddatic/sa2b-render-fix/assets/138042750/cd6b1217-0d46-43a8-a133-5c76c8d21ad9)

**Comment by shaddatic** [comment]
These ones haha? They _really_ don't want these to appear, I'm basically wrestling with the game just to get this

![213610_20230701151148_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/06f84ab9-8c62-4e32-9aa7-84a1b9cd844a)

**Comment by shaddatic** [comment]
They are finally restored as of version 1.2!

**Comment by LostImpactProd** [comment]
> They are finally restored as of version 1.2!

Awesome! When can we expect the latest download to be released?
