### ISSUE TITLE
Green Forest Tree Shadows

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#2]
In the Dreamcast and Gamecube versions of Green Forest, there were shadow textures present on the ground for certain trees in the level, but they seem to have disappeared in the HD ports.
You're able to easily tell where they're supposed to be since the lighting modifiers for those shadow textures are still present.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/d45c83a6-9229-427a-a634-e70ae768483a)
![image4](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/732c53e7-0ed7-4e45-b095-3436a06acf37)
![image3](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/527fad31-2afd-4325-80b1-8eb8bc3de7ae)
![image2](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/43677d9f-f15d-40ab-af88-5c2998bbe36c)

This issue is also in Sonic vs Shadow 1, but interestingly enough, it seems that the lighting modifier for the shadow is misaligned with the rest of the objects. (Please don't mind the other stuff with the water there. That's from another mod.)
![image5](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/6d5134b5-653b-4c2a-8578-cdb032003823)
![image6](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/7bf95ac8-74b2-4fc2-9f32-070287adbc0f)

**Comment by shaddatic** [comment]
This is an interesting issue. I'll be sure to look into this some once I've got some time. I'm imagining it's some misplaced function pointer or model, that wouldn't be out of the ordinary for these ports

**Comment by Ellasent** [comment]
I realize that I was mistaken on there being lighting modifiers present for those shadows, it was just the DC shadows mod being present that made them obvious in that way. It's not like it does much for the issue itself since it still persists, it's just something that I feel should be noted when it comes to playing without the DC shadows mod.

I also went ahead and checked to see if there was any sort of lighting modifier for the shadows in the Gamecube version, and I can confirm that there isn't any.
![image7](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/0d3331b8-0d3d-44ca-b12c-0c31d066d029)

**Comment by shaddatic** [comment]
Ahh, okay. So the "lighting modifier" is actually an object called MODMOD, and is basically a Dreamcast shadow that can be placed on the stage. The other lighting modifiers, ones that Dreamcast also use, instead unset the character lighting to get a similar effect.

I'm going to narrow the scope of this issue into _just_ the shadow textures, as restoring MODMOD is a seperate issue

**Comment by shaddatic** [comment]
That was one of the most random issues I've seen yet. The shadow texture is part of the tree model, but for some reason it was completely missing, removed - including it's texture entry in the texlist. Re-porting the model from Dreamcast and making a new texlist with the texture included appears to have restored it fully. I have no idea how or why SOC would do this, I'm completely baffled.

Not closing this issue yet as I want to do more research and testing before I consider the issue fully restored with no side-effects.

![213610_20230628023751_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/e084db85-13f2-4791-9f99-3c11127d2b85)

**Comment by shaddatic** [comment]
No side-effects and the model and texlist seem to load just fine in other stages too. Although changes to how it's done could be made in future, the feature is restored.

No further discussion needed on this issue, closing as complete.
