### ISSUE TITLE
Gohla is still tinted

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#23]
![GohlaSA2B](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/796be5e7-00ae-483c-8fd1-3a887d66e650)

**Comment by shaddatic** [comment]
Before I close this, are it's orbiting models also tinted?

**Comment by Ellasent** [comment]
It seemed pretty hard to tell just from looking at them given how vibrant the colors on them are, but they do seem to be a tinge darker in Battle.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/f1204da9-273a-4111-a888-06c5e2406132)
I just hope my eyes aren't playing tricks on me to see the difference.

**Comment by shaddatic** [comment]
Yep, they look tinted, I'll throw them in then close this issue. Thanks for the info!

**Comment by shaddatic** [comment]
Both confirmed fix, closing.
