### ISSUE TITLE
King Boom Boo Sun Door Calls From Wrong File

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#24]
I was initially not going to bring this up here since it seemed like it was going to be as simple as a single texture swap I could easily do, but as it turns out, it's a bit more complicated than that. The sun doors for King Boom Boo are supposed call from objtex_bossbogy, but instead, they seem to call from objtex_stg25, resulting in it using the wrong door texture.
![Battlesundoor](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/9828d8a7-aa7c-445b-a243-51dc4358f043)
![DCsundoor](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/90bf4d33-fe74-4d06-8a36-a878112b4d5d)
I even tested it out by replacing the corresponding texture in objtex_stg25 to be completely sure, and it checks out.
![Death Chamber sun door](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/2aba1aa0-6448-4568-8537-ceb2e90a778d)
![BattleDCsundoor](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/640f3a19-7d9c-4e54-897a-3f3f250a8a1e)

**Comment by shaddatic** [comment]
I've tracked down the issue! The two textures are basically fighting each other, and the last one loaded wins. This is different from Global Index and is due to how the textures are loaded into memory. I'll do some reordering and see what happens

**Comment by shaddatic** [comment]
Swapping the GVM table around fixed the issue. Closing.
