### ISSUE TITLE
Speed Lines

### ISSUE THREAD

**Issue by Lg1955** [shaddatic/sa2b-render-fix#27]
The speed lines on PC for running is slightly off in comparison to GameCube and Dreamcast

Dreamcast
https://github.com/shaddatic/sa2b-render-fix/assets/40836768/e2662017-ac60-499b-8231-69424677f06c

Gamecube
https://github.com/shaddatic/sa2b-render-fix/assets/40836768/00c6f2c3-3d15-4d0b-852d-08325fad36d6

PC
https://github.com/shaddatic/sa2b-render-fix/assets/40836768/4d8ebd41-20cf-46fa-9266-ac3ba13b946b

**Comment by shaddatic** [comment]
I'm not really sure what you mean purely looking at the videos

**Comment by Lg1955** [comment]
The effect on PC just looks like pixelated lines while on console look like actual white streaks
The compression on the videos kinda hide it, had to make the Gamecube and PC video to 480p because of the 10mb limit on videos

**Comment by shaddatic** [comment]
After looking deep into it and decomping all the effect code, I'm afraid that nothing can be done about this without completely rewriting the rendering code for them. The radius is just ignored, it can only do a single line of pixels and nothing more.

Maybe one day it can be overhauled, but until then this issue will remain open, but on low priority

**Comment by shaddatic** [comment]
In fact, I'm going to close this issue as a duplicate and merge it with issue #30, since they're practically the same issue my side. So any further comments should go there and not here
