### ISSUE TITLE
Weird Skybox Mapping

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#28]
In the HD ports, the most of the textures for the skyboxes are applied in such a way that makes it so they don't loop properly, making for a really ugly seam.
It effects the following stages:
City Escape
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/28a57fd7-5b31-4620-8703-18ad4c580c93)
Tails vs Eggman 1
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/91140e80-3703-4941-a6ef-c2c79d8889ef)
Metal Harbor
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/b8b328d2-9c76-4808-b573-c9f8c83c749e)
Green Forest
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/398e56e0-3c1a-45b4-8f93-cf9cae93a1ee)
Mission Street
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/900e2a20-2f24-45e0-bd22-eb86895d4e73)
Route 101 1st skybox
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/3f512da3-c731-46d5-a4a3-c045f5dac12f)
Radical Highway
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/40b7e4cb-72c3-4c38-8085-12a1a1cb535e)
Weapons Bed
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/84450692-f749-4d5f-b99a-5654dfe5c621)
White Jungle
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/4325fcd5-11a2-4751-9db1-b830ebd10932)
Route 280 1st skybox
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/5bcfa11c-9c62-4ae5-851a-18ac8c9e72c8)
Sky Rail
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/cd6a4aa9-2e40-4feb-b150-fcc49d6ddf26)
This does also affect some of the skyboxes in the cutscenes, but I'm willing to bet that's more so Cutscene Revamp territory there.

**Comment by shaddatic** [comment]
And this is a purely HD thing? Wasn't introduced in GameCube?

**Comment by Ellasent** [comment]
Yep! I made sure to check all of those cases on Gamecube and they were all alright there.
It's just wild seeing errors in the HD ports I thought applied to all versions of SA2B simply not being there on the Gamecube version.

**Comment by Ellasent** [comment]
I realized that I overlooked the 2nd skyboxes from Route 101 and Route 280.
![Screenshot 2023-07-04 004531](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/0c3bb011-e11d-470a-97af-4e0104a515a8)
![Screenshot 2023-07-04 004910](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/27005351-46f0-4706-9652-9f10de0cc369)
This was thanks to the fact that I noticed the ones for the extra kart race stages, which made me want to double check.
![Screenshot 2023-07-04 003445](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/6ff0f132-668a-4405-a2dd-3ba2c69f0315)
![Screenshot 2023-07-04 003608](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/43c6f3e3-6850-4d75-815d-1d4db97758d7)
![Screenshot 2023-07-04 003953](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/21d1deef-8f11-4bc9-8bdf-542f1a30ba21)

**Comment by Ellasent** [comment]
This seems to be fixed with the latest dev updates, meaning it likely was the same issue as the other UV errors.
Regardless, glad to see it taken care of.
