### ISSUE TITLE
njDrawLine3DEx is only 1px wide

### ISSUE THREAD

**Issue by Lg1955** [shaddatic/sa2b-render-fix#30]
Seems similar to this issue where the PC looks like a line of pixels while it doesn't on Dreamcast and Gamecube https://github.com/shaddatic/sa2b-render-fix/issues/27

Dreamcast
https://github.com/shaddatic/sa2b-render-fix/assets/40836768/642fd94c-4090-4048-a395-4ecb823ed381

GameCube 
https://github.com/shaddatic/sa2b-render-fix/assets/40836768/3a4d982a-edd9-4554-b843-1422ab6eaa1e

PC
https://github.com/shaddatic/sa2b-render-fix/assets/40836768/7a00efd5-ab04-448b-b351-f7b2821077c3

**Comment by shaddatic** [comment]
I managed to get high quality images of Dreamcast and PC in the same spot. Are you talking about the size of the lines?

![Untitled-1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/b63bd77d-1767-48a0-a19a-f009f8f87e59)

**Comment by Lg1955** [comment]
Yes, the PC has very thin, basically 1 pixel thick lines, and with the resolution of both at 480p, Dreamcast and GameCube still have better looking lasers

**Comment by shaddatic** [comment]
Reposting my comment under 'Speed Lines' issue:

"After looking deep into it and decomping all the effect code, I'm afraid that nothing can be done about this without completely rewriting the rendering code for them. The radius is just ignored, it can only do a single line of pixels and nothing more.

Maybe one day it can be overhauled, but until then this issue will remain open, but on low priority"

**Comment by shaddatic** [comment]
I've created a custom line drawing function for Render Fix allowing for custom line widths. This has allowed be to completely replace the game's line drawing function, finally resolving this issue! I will close it once I've pushed the feature to the repo!

![image](https://github.com/user-attachments/assets/21223a5b-7dec-448e-8b64-3c3a67faabfc)
