### ISSUE TITLE
Another White Jungle "Restore Tree Jungle Object" crash possibly spotted in v1.1.1

### ISSUE THREAD

**Issue by cnrm** [shaddatic/sa2b-render-fix#35]
More than halfway through White Jungle I've observed another crash occurring, seemingly similar to the one that was fixed in the v1.1.1 update.

This has been reproducible 100% of the time, and I've made sure no other mods are enabled while testing. Disabling **Restore Tree Jungle Object** resolves the crash.

Using SA2 Mod Manager's Test Spawn with position coordinates around **X: 9098, Y: -3154, Z: -4913** with the tree jungle object setting enabled can instantly trigger the crash. Alternatively, **X: 7155, Y: -1937, Z: -3765** can spawn shortly before the crash point to see it in action.

![nkybE4y](https://github.com/shaddatic/sa2b-render-fix/assets/5803611/f686e51b-0fde-42a8-b5d6-f3855fa6682c)

**Comment by shaddatic** [comment]
This tree will be the death of me

**Comment by shaddatic** [comment]
Fixed in coming hotfix update, closing
