### ISSUE TITLE
Sky Rail Cloud Layers

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#36]
I noticed that there are extra layers of clouds scrolling in the Dreamcast version of Sky Rail that's missing in Battle.
![ezgif com-optimize](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/9b81c668-4007-4f5d-9502-9fa7305a4d75)
![ezgif com-optimize(1)](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/b0eb827e-8e52-4d6f-b290-c8ac56e3ae8d)

**Comment by shaddatic** [comment]
If I had to make a wild guess, I think they're still there but rendering in the wrong order - and due to lacking any form of transparancy sorting, one of the layers ceases to exist. I will look into this further

**Comment by shaddatic** [comment]
I was 100% correct, will be included in the coming hotfix. Closing
