### ISSUE TITLE
Pumpkin Hill Cloudy Effect

### ISSUE THREAD

**Issue by spidergrear2** [shaddatic/sa2b-render-fix#37]
Could be related to transparency issues, in DC Pumpkin Hill has a cloudy effect on the ground, this effect is not present in Battle.
DC:
![cloud9](https://github.com/shaddatic/sa2b-render-fix/assets/77766023/3dd9cd3a-6ce0-47fd-8d31-26b649ccb73a)
Battle:
![cloud99](https://github.com/shaddatic/sa2b-render-fix/assets/77766023/537af6ab-ccd3-4614-8fbb-7c74528d25d9)
Also, i think battle uses a lower quality texture on the clouds.

**Comment by shaddatic** [comment]
Hmm, it doesn't look like transparancy order issue from here but I'll look into it, it still very well could be

**Comment by shaddatic** [comment]
It wasn't related to transparancy for once! It might be slightly related, but it was just a general draw order issue. Drawing the background elements later fixes it! Closing issue
