### ISSUE TITLE
Skateboard/rail grinding particles are too small, almost invisible at higher res

### ISSUE THREAD

**Issue by Sonikko** [shaddatic/sa2b-render-fix#38]
Seems to be resolution dependant

PC 576p (my monitor wont go lower)
![photo_2023-07-05_13-44-17](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/2e294f83-de6b-4055-ad5f-9d817388334a)

PC 4k
![photo_2023-07-05_13-44-20](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/f30fbb0c-1647-4238-a8b4-a82ddba1541e)

PC 576p
![photo_2023-07-05_13-44-25](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/db56035c-f079-461a-9372-8baa30450f51)

PC 4k
![photo_2023-07-05_13-44-26](https://github.com/shaddatic/sa2b-render-fix/assets/24740235/34ad2027-11fb-4ead-b2ee-d266fca72ba8)

**Comment by shaddatic** [comment]
I'm aware of this issue. Not sure anything can be done about this, but I will look into it

**Comment by shaddatic** [comment]
I managed to make the scale of the particles independent from the resolution! They do look rather blocky now though, so I'll include some user settings for scaling - likely 100%, 50%, and 25% scaling options.

Closing as complete! Thanks for the report

![213610_20230706193931_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/573735e7-a046-414c-9b03-12b85b4ffce8)

**Comment by TorutheRedFox** [comment]
> PC 576p (my monitor wont go lower) ![photo_2023-07-05_13-44-17](https://user-images.githubusercontent.com/24740235/251139402-2e294f83-de6b-4055-ad5f-9d817388334a.jpg)

oh I'm sure it will but Windows probably isn't letting you as it's a software block that you can get around (mine didn't support 120Hz until I just added the display mode and it works just fine as it's a 144Hz monitor)
