### ISSUE TITLE
Emblem Sparkle Effects

### ISSUE THREAD

**Issue by toonjoey** [shaddatic/sa2b-render-fix#4]
Emblem sparkles display in the incorrect order on the HD ports, resulting in them--rather than orbiting around the emblem--constantly staying behind the emblem.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/19507339/f3e45cde-05e0-41bb-8e9c-73e966a264a2)

**Comment by shaddatic** [comment]
I've been able to confirm that this bug occurs on the GameCube version too. That hopefully means the solution will be rather simple, but it will be looked into either way

**Comment by shaddatic** [comment]
After some matreial edits and a displayer switch, it's rendering correctly again. Will be included in the next update and will be pushed to the main branch soon.

No further discussion needed, closing this issue.

![213610_20230628043956_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/769cf6de-4a48-47b8-b862-671537a67784)
