### ISSUE TITLE
Transparency of menu backgrounds

### ISSUE THREAD

**Issue by TorutheRedFox** [shaddatic/sa2b-render-fix#45]
The HD releases have custom background rendering code in place that for some reason doesn't support transparency. This results in background transitions being reduced to the background instantly swapping over, fadeouts to black when entering and exiting different menus, etc. to break, and the janky hack of the SA2B title screen background being just disabled when entering the main menu instead of fading out to near-transparency.

The only conditions where the fading works as intended are when you are running the game both in 4:3 and with the Battle menu backgrounds, as that just makes it use the original (and functional) GameCube code instead.

**Comment by shaddatic** [comment]
I'm still not sure myself what causes these issues, but I'll go with your hunch on transparancy ordering. We can't just use the GameCube stuff though, as it's in the wrong aspect ratio and would look more broken. This issue will be looked into more though

**Comment by TorutheRedFox** [comment]
the gamecube stuff _could_ be used by sneakily modifying the projection matrix before background renders then popping it back, but then the dreamcast stuff would need porting for no battle mode

**Comment by TorutheRedFox** [comment]
actually porting DC stuff over would restore DC menu themes as a little bonus too

**Comment by TorutheRedFox** [comment]
the story select background fades correctly on Xbox 360 but I haven't observed other menu crossfades working correctly

**Comment by TorutheRedFox** [comment]
> the story select background fades correctly on Xbox 360 but I haven't observed other menu crossfades working correctly

it only fades correctly without the battle dlc

wtf

**Comment by shaddatic** [comment]
This issue was fixed in the last commit

**Comment by TorutheRedFox** [comment]
:tada:
