### ISSUE TITLE
Pyramid Cave Object Rendering Order

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#46]
Several objects throughout Pyramid Cave seem to render behind all other objects.
The common link between all of them are that they're 2 dimensional objects. Many of them to contain aspects of transparency as well so I hope it's more of an ordering issue than a transparency issue, but I thought I should mention that.
The first and most noticeable one is the light coming from the lamps found throughout the stage.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/72e4c0f6-032e-4aed-b451-d51d5daf02f2)
Next up are the chains that hold many objects up.
![Screenshot 2023-07-05 184357](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/fc5760c3-8d5f-42f2-9a48-fe864dbee75a)
Then there's the cobwebs.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/60d7f5e3-ff8f-4414-add5-c3c0543ce9c3)
Last but not least are the flames that burst from these statues, and only these flames. None of the other ones seem to have this problem.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/b9e4c28e-2148-4dcf-8be2-c15a8f60965c)

**Comment by shaddatic** [comment]
A lot of these are probably unfixable, at least within the scope of this mod. Maybe if #1 makes a triumphant return we'll finally see this put to bed

**Comment by shaddatic** [comment]
All of these issues are fixed as of 1.2!
