### ISSUE TITLE
Objects not showing up behind transparent object in Pyramid Cave

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#47]
I have this one separate from the rest since it seems to be a slightly different situation.
It probably has to do with the fence being drawn first and then the bits of the other objects that you would see when the fence is opaque.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/729b2898-2700-43df-83de-8f5d84fd66bb)

**Comment by shaddatic** [comment]
Very very likely. Sadly nothing can be done about this as they're two seperate objects. I will have a dig about though, maybe I can do something about it. Will have to wait for issue #1 to be re-implimented for these issues to be truly fixed

**Comment by shaddatic** [comment]
Adding the object to the sorted display list mostly resolved this issue! Closing

![213610_20230718144347_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/86260785-6c7c-4890-98c8-47c6f97e19e4)
