### ISSUE TITLE
Missing White Jungle Water Layer

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#48]
In SA2B, there was supposed to be a layer of water that would use the textures from BGTEX04 to make it so it looked like the raindrops were hitting the water. I remember having scene this before while playing the PC version of the game, but these days it's never there. I was originally glad about that for reasons I'll likely cover in a tangentially related issue, but now that I realize that it might be possible to fix that, I'd like to have that water layer back in the first place.
After checking the Gamecube, PS3, and Xbox 360 versions of Sonic Adventure 2 Battle, they don't seem to have that water layer visible either. I even uninstalled the mod loader to check and see if an unmodified version of PC SA2B would have it, and it didn't.

I know for a fact it's there, I just wish I had a screenshot to show exactly what I mean.

**Comment by shaddatic** [comment]
Do you have any further info? I'm really unsure what you mean, and if it's not on any version then it sounds like possibly a mod added this? Are you talking about water ripples, or the fog texture on the water?

**Comment by Ellasent** [comment]
Basically, under the regular water layer that's always there, the whole extra layer of water is there.
I think it may have been a mod that made it pop up, but I know that there's textures for it in the base game, and it's mapped to an area that otherwise you don't see.
The textures I was talking about in BGTEX04.prs look like this.
![whiterain](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/4fac753e-32f4-409f-b9eb-001e9e30ff44)

It seems that what caused the thing to actually show up was this old AI upscaled texture mod. I've since then stopped using AI upscaled textures just because I think the original textures just tend to work better, but I remember the big thing here was that this came out before the Highest Quality Textures mod which fixed several things when it came to the layering of replaced textures. So when using this mod there was extra errors caused by the whole thing. But it seems like something about that was able to uncover the whole thing underneath the original water layer.
![Screenshot 2023-07-14 232635](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/ca2bd6c3-409c-43a4-98d5-d2b61525cc4a)

Here's the link to the mod as well if you want to see what the heck is up with it that makes this happen.
https://www.moddb.com/mods/sonic-adventure-2-neuro-ai-hd-texture-pack/downloads/sonic-adventure-2-neuro-ai-hd-texture-pack-v10
I don't know why they didn't decide to utilize this. I could only assume it's something like the fact that it's a bit lower than the previous water thing which would make it a bit weird when it comes to objects protruding from the water since it shows two layers of water from those.
But yeah, this was all I was able to uncover about the whole thing. So I hope it just shows off this whole thing for this enhancement.

**Comment by shaddatic** [comment]
You'll be happy to know I actually figured this out and got it back haha! However, after fixing the draw order, the effect is very slight - likely why the devs, and most of everyone else, missed it
![image](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/5a3e2863-9be3-4a6f-b911-fe3cdd03f5e5)

**Comment by shaddatic** [comment]
Yeah, this was _intended_ to be part of the Battle port, but it draws in the wrong order causing the effect to never appear. The mod you used sets the water texture to use the 'Alpha Sort' flag, which essentially means it will be force-drawn but _above_ the mist layer. By setting the flag and fixing the draw order, the effect is now restored as intended. Fixed!
