### ISSUE TITLE
njSetBackColor is ignored, always black

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#49]
In the Dreamcast version of the game the back color for Knuckles' section of Cannon's Core is orange so that it can blend in with the underwater section.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/6cf53dc9-6424-4383-97f5-869c9d9a8b58)
Since the back color is black in Battle, it makes the pit look really jarring underwater.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/2d07e222-8883-47d7-91b3-0cb6fb96960a)

**Comment by shaddatic** [comment]
I'm aware of this issue, and looking into it atm. I'm pretty sure I've restored it, but I need to make sure I didn't break anything in the process

**Comment by shaddatic** [comment]
Another instance of this issue is in Sand Ocean, and can be seen right at the start. Left side is DC, right is PC

![image](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/36098828-ab4a-4535-ac02-018b89cf583b)

**Comment by Ellasent** [comment]
I'll be honest, this was actually inspired by seeing you tackle this issue in Hidden Base. It just made this one immediately spring to mind when before I thought it involved some kind of fog function exclusive to the Dreamcast version. I'm just glad it's a bit of an easy fix.

**Comment by shaddatic** [comment]
This issue is fixed as of version 1.2, but I've also restored the original Dreamcast functionality of the back-color!
