### ISSUE TITLE
Results Screen Rendering Order

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#5]
This is definitely one of the more minor things, and honestly it's a fix I personally won't find myself using since I actually like the effect it causes, but I figure it should still be brought up.

In the Dreamcast version of the game the actual boxes containing all of the info of the result screen is a lot brighter than in Battle.
![image10](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/f0ed5570-b532-4d22-9675-2b73d7754c50)
This is due to how in Battle, those boxes are actually rendered behind the darkened screen filter. I always had a suspicion this was the case until I fully confirmed it by just booting up the game in 240p for no particular reason, which caused that the screen filter to only show up in the corner, and with that, being able to see those boxes have the same colors they do on the Dreamcast.
![image11](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/6f985a1a-fe62-40b0-9330-6e5fb1569b11)
Hopefully this should be a pretty easy render reordering thing there.

**Comment by shaddatic** [comment]
At first glance, this issue is possibly related to issue #1. Probably an easy but messy fix, but either way it will be looked into.

**Comment by toonjoey** [comment]
I also have to add on that a similar issue is present with the main game HUD, along with said HUD not fading out like in the Dreamcast version.

**Comment by shaddatic** [comment]
With a bit displayer switching, I've got it rendering correctly again! I'll take note of the HUD thing too, althought that's a seperate issue
![213610_20230918185452_1](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/6f7240a9-b0aa-439c-a138-a4c72a744bde)
