### ISSUE TITLE
Rocket Button Still Tinted

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#56]
The button of the rocket object is still tinted.
![Screenshot 2023-09-08 140428](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/083b2ee0-baa9-45fa-aebb-116e37c65a2e)
![Screenshot 2023-09-08 140449](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/d0b1a448-c37d-4c5e-841a-9f17384af51b)

**Comment by shaddatic** [comment]
Yes, I do remember fixing this model and the whole button went black. I'll look into this further when I have time. Do also remember that it still will look darker due to missing specular

**Comment by shaddatic** [comment]
Found what was causing the black issue and added the model to the tint-fix list!
![image](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/e88d597b-0f73-417e-913b-9fdc093867c5)
