### ISSUE TITLE
The game crashes whenever I try to open it with the mod checked

### ISSUE THREAD

**Issue by Cton95** [shaddatic/sa2b-render-fix#58]
When I check Render Fix regardless of it's position on my mod priority or if it has other mods around it or not and select Save and Play, the game crashes after the Sonic Team logo saying "SA2 has crashed at 42fce 1 (sonic2app.exe)."

Is there any way to fix that issue whether with the most recent version or if not then could you try a resolve it in a future update?
This didn't happen to me before 1.2.2.

**Comment by shaddatic** [comment]
I'm unable to recreate the crash. However, I don't recommend using "Save & Play," as it has caused issues with the game, such as crashing, in the past. I'm unsure if these have been fully resolved

**Comment by shaddatic** [comment]
Closing due to no further information

**Comment by SonicdomXD** [comment]
Hello, just going to bring up the issue again. Normally when I am playing the game on my steam deck without the mod turned on, everything goes fine, but if the mod were to be turned on, it either refuses to start or crashes entirely. I'll provide my crash report later.
