### ISSUE TITLE
Upgrades Ignore Draw Order in Cutscenes

### ISSUE THREAD

**Issue by NikkMann** [shaddatic/sa2b-render-fix#60]
The models for character upgrades seem to render on top of everything in cutscenes. This does not happen in the DC version of SA2. Might happen in gameplay too, harder to test there because there aren't as many on-screen elements that draw over everything, but the upgrades do correctly render below fog and white smoke in gameplay so there's that.

Happens even with Cutscene Revamp.

PC
![sonic2app 2023-10-23 13-49-52](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/90e0b3b3-7c49-43c9-9871-c7864674bf51)

DC (he has the metal knuckle and necklace upgrades on, can't see it too well cause they're rendered below the glow as they should be)
![image](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/36dc6f9f-5d6f-46b2-9a64-67282a3c1fc8)

**Comment by shaddatic** [comment]
This is on the fix list, I even know how to fix it, so it's days are numbered

**Comment by shaddatic** [comment]
This was fixed in the last commit

**Comment by shaddatic** [comment]
I'm going to reopen this issue. While it was fixed, it never made it to the release version of the mod
