### ISSUE TITLE
Modifier Shadows Draw Over Effects in Events

### ISSUE THREAD

**Issue by NikkMann** [shaddatic/sa2b-render-fix#61]
Not sure if this falls under your scope, but we talked (on gamebanana) about how you have pseudo-support for the DC Shadows mod with your Render Fix mod.

Well, the DC Shadows ignore draw order and appear to always render on top, both in game and in cutscenes. They don't do this in the actual DC game.

PC
![sonic2app 2023-10-23 14-02-01](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/ba895c50-69e5-4cc7-92c4-e33adab73fc7)

DC
![image](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/419900cb-d45b-4b9c-926a-e3dc6ca59919)

PC
![sonic2app 2023-10-23 14-29-03](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/260609f4-b373-4f7e-bd45-fc5ac3784ea9)

DC
![image](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/5dbbd3e2-f993-484d-94d8-be5f7190df17)

PC (can also see upgrade models clipping through like in my other issue post)
![sonic2app 2023-10-23 14-29-56](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/2b47777f-6643-49bf-a96d-1e0c3074fb0d)

DC (the same shadow from PC is there, but you can't see it cause its correctly covered by the green glow)
![image](https://github.com/shaddatic/sa2b-render-fix/assets/90150509/f4e2ea7d-52c8-4ec6-985f-e024d0058fd1)

**Comment by shaddatic** [comment]
DC shadow is now a part of Render Fix, as such I'm going to reopen this issue and re-orient it toward specifically the event issues. However, the issue in the water is not draw order related and instead fog related, so I will make it a seperate issue.

**Comment by NikkMann** [comment]
Awesome to hear! 
If you don't remember, I had a comment before describing how your extra shadows option covered objects that DC Shadows did not, and vice versa. Hopefully you adding in DC Shadows will mean that all objects are properly covered, including stuff in cutscenes like the prison bars when amy breaks sonic out of the jail cell.
Here was that post for more detail: https://gamebanana.com/posts/11185026

**Comment by shaddatic** [comment]
Those issues have been covered and are fixed
