### ISSUE TITLE
shadows head red stripe broken

### ISSUE THREAD

**Issue by horay133** [shaddatic/sa2b-render-fix#63]
when using a mod like Dreamcast models or dc+ models shadows head red stripe break
![Screenshot_770](https://github.com/shaddatic/sa2b-render-fix/assets/57258910/8f985310-a524-4f63-8f79-e7f8e2f33e52)

**Comment by shaddatic** [comment]
This picture is from the Dreamcast version, it's weird but it is working as intended
![image](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/4ee0a7d2-c2f9-449d-a524-8bf6eac6a9ec)

**Comment by horay133** [comment]
very weird
