### ISSUE TITLE
Glitchy Textures

### ISSUE THREAD

**Issue by san7326** [shaddatic/sa2b-render-fix#66]
I've come across 2 textures glitches.
One at Tails VS Eggman 2, where the stars don't appear:
![Screenshot_12](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/65b6e30e-f5d7-4dd5-9c10-7c692779676d)

And the other at Knuckles' Cannon's core, where it has this yellow texture:
![Screenshot_13](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/bfd4bed8-a1df-4548-8130-f5dc2e220dfd)

These only appear with this mod (it's the only mod I have turn on)

**Comment by shaddatic** [comment]
That's backface culling, I'll note them down and have them fixed for the next version!
