### ISSUE TITLE
Glitched number textures in kart racing

### ISSUE THREAD

**Issue by DeadCell33** [shaddatic/sa2b-render-fix#69]
I noticed that the front number texture on default karts for Sonic, Tails, Knuckles, Shadow, and Rouge all get cut off and show only half of it, and for Eggman both numbers has a white square around them. Looking at videos online this wasn't an issue on DC but has since been from Battle on GC and the HD versions. I had no mods on when I checked the Steam version.
![65b57b62de512](https://github.com/shaddatic/sa2b-render-fix/assets/113919121/c15374f8-80c0-4f52-bae8-8a3c38ea880d)
![65b57b682990d](https://github.com/shaddatic/sa2b-render-fix/assets/113919121/e6d94fac-81a0-49c6-b1fb-5778761bd7d2)

**Comment by shaddatic** [comment]
I was half aware of this ~~I honestly thought RF had caused it~~, but now I know it's vanilla I have a good idea about what's wrong but I don't have a good plan atm on how I'll go about fixing it

**Comment by shaddatic** [comment]
This is fixed as of 1.3.3
