### ISSUE TITLE
Dreamcast Menu Effects

### ISSUE THREAD

**Issue by Meepmeep189** [shaddatic/sa2b-render-fix#76]
I know this might be more relevant to the No Battle Mod, but on Dreamcast, there were much smoother transitions between menus. After the logo animation finished, it would fade into and out of white and each menu screen would smoothly crossfade between different backgrounds, all with the same sonic & shadow pattern. Presumably Battle removed this smooth transition effect and it carried over into the PC release. Any chance it could be restored?

[https://youtu.be/V2W4osYAlkE?si=naw8I6vPgRVDRigo&t=29](url)

**Comment by shaddatic** [comment]
I'm going to assume you're refering to the Battle menus, in which case this is fixed. Closing.

**Comment by Meepmeep189** [comment]
Sorry for the late reply. I was referring to the Dreamcast Menus. There's a brief black jump cut rather than a crossfade.

**Comment by shaddatic** [comment]
Okay, I think I see it. I'll look into it, reopening

**Comment by Meepmeep189** [comment]
thanks for fixing this :)
