### ISSUE TITLE
Inconsistent Shadows and Lightning 

### ISSUE THREAD

**Issue by san7326** [shaddatic/sa2b-render-fix#79]
When exiting (and restaring but it happens rarely) Metal Harbor and Crazy Gadget, there's a problem with the shadows and the lightning.

Shadows (Metal Harbor)
![Screenshot_27](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/a197db1e-7c28-4c2d-879b-54c14e109f63)
![Screenshot_30](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/8c3417fb-cc17-4a0a-a72c-8609725ca4f1)

Lightning (Crazy Gadget)
![Screenshot_31](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/6a18b17e-c745-4862-be53-6a5c292e2473)
![Screenshot_32](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/514d54cd-5540-47ac-8eb7-e1cd14d91c18)

**Comment by shaddatic** [comment]
After trying for a few minutes, I couldn't reproduce this result. Could you list the exact steps you take? And could you attempt to reproduce the result with only Render Fix enabeld?

**Comment by san7326** [comment]
![Screenshot_33](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/c5dcb500-76a9-43ab-8566-2a3e865827eb)
![Screenshot_34](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/76ce700f-12eb-4bf2-9d18-6c22ab96d02f)
![Screenshot_35](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/f75a0f30-f487-40a9-9109-528dce2716b1)
![Screenshot_36](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/aa6b1bc6-b18c-4173-abbf-3eb55b9f3cfe)
Here's with Render Fix

**Comment by shaddatic** [comment]
I managed to recreate it. No idea what's causing this, and I also haven't yet tested on Dreamcast and GameCube

**Comment by shaddatic** [comment]
Found the issue; the global light manager never destroys itself correctly, meaning it can only be loaded once and then never works again. Nice find! This was likely an issue on GameCube too
