### ISSUE TITLE
Cannon's Core rotating cogs

### ISSUE THREAD

**Issue by LostImpactProd** [shaddatic/sa2b-render-fix#8]
Not really a render fix as such, but further to [Ellasent](https://github.com/Ellasent)'s post about the pit in Rouge's Cannon's Core section, I think it would be nice to see the rotating cogs in Sonic's section restored from the DC version too.

![SonicAdventure2_CannonsCore2](https://github.com/shaddatic/sa2b-render-fix/assets/138042750/0febe5a4-e7db-4529-8d22-55f337f82e02)

![SonicAdventure2Battle_CannonsCore2](https://github.com/shaddatic/sa2b-render-fix/assets/138042750/74777d00-7313-4582-8558-7cbf186759f9)

**Comment by shaddatic** [comment]
Finally, after all these years, fixed! Thanks goes out to End User who took the first steps toward fixing this a few years ago

![image](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/dfeca296-ed00-4160-8ed1-bc6fad47f893)
