### ISSUE TITLE
Dry Lagoon Glass Pillar

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#83]
I decided to separate this from the other Dry Lagoon stuff since it's technically a 1-2 punch of backface culling and transparency order stuff.
In the vanilla game this pillar has sorting issues with itself.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/6878c9e6-98a3-439f-9c2c-3842d37c6225)
While I understand that this object being culled makes the rendering order technically a non issue, I believe that this is an object that'd benefit much more from having the sorting fixed rather than keeping it culled.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/7b11aa72-3f50-4e14-83e4-e548b9bb69ba)

**Comment by shaddatic** [comment]
The transparancy sorting issues will be addressed at a later date. I've got a few ideas on how to solve all issues like this with one feature

**Comment by Ellasent** [comment]
Sounds interesting!
Can't wait to see what it is sometime down the line.
