### ISSUE TITLE
Mission Street Lights Rendering Order

### ISSUE THREAD

**Issue by Ellasent** [shaddatic/sa2b-render-fix#85]
Various lights in Mission Street seem to render behind other objects,
Specifically the fence lights and both types of police car lights.
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/3fcaf5c2-2d14-4229-a910-d05165a2aada)
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/9760295d-7d80-4616-acf1-c2e295cea2eb)
![image](https://github.com/shaddatic/sa2b-render-fix/assets/62478552/35d16fad-03ef-4165-8512-4f5b727cca40)

**Comment by shaddatic** [comment]
I've managed to improve the situation, but for some reason its still struggling with the tires, they just refuse to draw over them, even on other vehicles. Very strange

![image](https://github.com/shaddatic/sa2b-render-fix/assets/65688998/c8bef20a-88ea-4aa5-8d5c-114fa3020caf)

**Comment by shaddatic** [comment]
Ah, its because it's a Ginja model... Well, I'll consider this fixed and closed, and hopefully the issue with the tires will be fixed when these cars get converted back into Chunk format
