### ISSUE TITLE
Models in Mini Cutscenes Still Tinted

### ISSUE THREAD

**Issue by san7326** [shaddatic/sa2b-render-fix#89]
The models are still tinted in the mini cutscenes. 
DC
![Screenshot_48](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/f9a2e168-1bbd-4261-be6b-e56f0a89f0ee)
PC 
![Screenshot_44](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/a2c627e0-4572-4d52-a2d4-8e86d895ff50)

DC
![Screenshot_42](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/2abad64a-a956-4d23-b77e-9835ad1e1a31)
PC
![Screenshot_47](https://github.com/shaddatic/sa2b-render-fix/assets/79737847/ef5b2d7c-1c81-4a47-ac24-9753f902668a)

Render fix is on.

**Comment by shaddatic** [comment]
Mini-events aren't yet easily editable, I'll give it a look next major update but not for 1.3

**Comment by shaddatic** [comment]
As of 1.3.3, due to the new Chunk draw function and it's Dreamcast emulation features, this issue is now fixed!
