### ISSUE TITLE
Emblem Screen Transition Missing

### ISSUE THREAD

**Issue by toonjoey** [shaddatic/sa2b-render-fix#9]
The Dreamcast version of the game has a short fade-in effect on the emblem screen that's missing in every other version of the game.

https://github.com/shaddatic/sa2b-render-fix/assets/19507339/39b13fe2-f540-449e-bd9a-0bbcee19af6c

**Comment by shaddatic** [comment]
After looking at the code, everything for this feature to work still exists but the screen fade is set to 0 before any of it can execute. Removing this mov operand completely restores the feature. It will be included in the next update. Closing as complete.
