### ISSUE TITLE
Misaligned Life Icons in Kart Stages

### ISSUE THREAD

**Issue by St0rmFlag** [shaddatic/sa2b-render-fix#97]
On PC, the life icons become misaligned when playing on the Kart stages. This isn't the case in DC or GC.

![Presentation2 (2)](https://github.com/shaddatic/sa2b-render-fix/assets/168741602/345d206c-b34a-4d24-8849-8b0d35195259)

**Comment by shaddatic** [comment]
Is this still the case in 4:3?

**Comment by St0rmFlag** [comment]
> Is this still the case in 4:3?

Yes it is.
