### ISSUE TITLE
Water Particles not working after 1.3.0.1

### ISSUE THREAD

**Issue by Lg1955** [shaddatic/sa2b-render-fix#99]
After the 1.3.0.1 update, water particles fix seem to have broke 

1.2
![image](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/1e9bb5d4-6270-44f8-864f-a270fa981387)

1.3
![image](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/eb7a7e17-1cab-41ac-8284-b72d9ad0de10)

1.3.0.1
![image](https://github.com/shaddatic/sa2b-render-fix/assets/40836768/0bb7c2d3-e964-4ce3-afe3-c2d2ea3ad6da)

**Comment by shaddatic** [comment]
This is a strange one, no changes made in that hotfix have anything to do with this feature...

**Comment by shaddatic** [comment]
Nvm, figured it out. Will have this fixed shortly
